// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQqLVRd14GZ1FFCUzxVMrcz3oqPGbZfg',
    appId: '1:628060845023:web:a2de6e78bc4b9b0f248a6a',
    messagingSenderId: '628060845023',
    projectId: 'pet-lovers-fefitti',
    authDomain: 'pet-lovers-fefitti.firebaseapp.com',
    storageBucket: 'pet-lovers-fefitti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_-ppGEpReDRKPJWPM6mvd-4hAX2EZ2I',
    appId: '1:628060845023:android:77da92e1e223c1f3248a6a',
    messagingSenderId: '628060845023',
    projectId: 'pet-lovers-fefitti',
    storageBucket: 'pet-lovers-fefitti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcwtePAomtucWbk8bCEaCOiS4njC9z-A',
    appId: '1:628060845023:ios:e562ad256abf9ef9248a6a',
    messagingSenderId: '628060845023',
    projectId: 'pet-lovers-fefitti',
    storageBucket: 'pet-lovers-fefitti.firebasestorage.app',
    iosBundleId: 'com.example.petLovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPcwtePAomtucWbk8bCEaCOiS4njC9z-A',
    appId: '1:628060845023:ios:e562ad256abf9ef9248a6a',
    messagingSenderId: '628060845023',
    projectId: 'pet-lovers-fefitti',
    storageBucket: 'pet-lovers-fefitti.firebasestorage.app',
    iosBundleId: 'com.example.petLovers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQqLVRd14GZ1FFCUzxVMrcz3oqPGbZfg',
    appId: '1:628060845023:web:30cadd95b3de8f2b248a6a',
    messagingSenderId: '628060845023',
    projectId: 'pet-lovers-fefitti',
    authDomain: 'pet-lovers-fefitti.firebaseapp.com',
    storageBucket: 'pet-lovers-fefitti.firebasestorage.app',
  );
}
